//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CTPL.ERP.Local.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Internal_Sims_Activations
    {
        public string ICCID_1 { get; set; }
        public string ICCID_2 { get; set; }
        public string ICCID_1_Network { get; set; }
        public string ICCID_2_Network { get; set; }
        public Nullable<long> IMSI_1 { get; set; }
        public Nullable<long> IMSI_2 { get; set; }
        public Nullable<long> MSISDN_1 { get; set; }
        public Nullable<long> MSISDN_2 { get; set; }
        public string ESN { get; set; }
        public Nullable<System.DateTime> BootstrapActivationStartDate { get; set; }
        public Nullable<System.DateTime> BootstrapActivationEndDate { get; set; }
        public Nullable<System.DateTime> AllocatedToInHouseDate { get; set; }
        public string APN_Name { get; set; }
        public string IP_1 { get; set; }
        public string IP_2 { get; set; }
        public string IP_3 { get; set; }
        public string IP_4 { get; set; }
        public string MN_1 { get; set; }
        public string MN_2 { get; set; }
        public string MN_3 { get; set; }
        public string MN_4 { get; set; }
        public string IMEI { get; set; }
        public string For_User { get; set; }
        public string For_State { get; set; }
        public Nullable<System.DateTime> Dispatch_Date { get; set; }
        public string Dispatch_Location { get; set; }
        public string Remarks { get; set; }
    }
}
